2018-12-24 23:44:00,181 ERROR: Exception on /index [GET] [in c:\homework\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\homework\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\HomeWork\app\routes.py", line 19, in index
    return render_template('index.html', title='Главная страница', form=form, posts=posts)
  File "c:\homework\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\homework\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\homework\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\HomeWork\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\HomeWork\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\HomeWork\app\templates\index.html", line 7, in block "content"
    {{ form.hidden_teg() }}
jinja2.exceptions.UndefinedError: 'app.forms.PostForm object' has no attribute 'hidden_teg'
2018-12-24 23:45:31,888 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-25 00:04:30,335 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-25 00:04:39,958 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-26 22:59:39,592 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-26 22:59:55,291 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-26 23:00:06,206 ERROR: Exception on / [GET] [in c:\homework\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\homework\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\HomeWork\app\routes.py", line 21, in index
    if post.has_next else None
UnboundLocalError: local variable 'post' referenced before assignment
2018-12-26 23:01:45,664 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-26 23:08:05,109 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-26 23:20:20,588 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-26 23:20:32,204 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-27 00:49:22,235 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:29]
2018-12-27 00:49:26,724 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:29]
2018-12-27 00:50:12,552 ERROR: Exception on /login [GET] [in c:\homework\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\HomeWork\app\routes.py", line 44, in login
    return render_template('login.html', title='Вход в учетную запись', form=form)
  File "c:\homework\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\homework\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\homework\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\HomeWork\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\HomeWork\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\homework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\homework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\homework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\homework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\HomeWork\app\templates\base.html", line 45, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\HomeWork\app\templates\login.html", line 13, in block "app_content"
    <p>Вы забыли пароль?<a href="{{ url_for('reset_password_request') }}">Нажмите тут чтобы сбросить пароль</a></p>
  File "c:\homework\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\homework\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\homework\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
